name: "Job"
description: ""
runs:
  using: "composite"
  steps: 
  - run: |
      echo "Executing action"
      ls -la
    shell: bash

  - name: test 
    run: |
        echo ${{ context.steps.secrets.outputs.GCP_PROJECT_ID }}
    shell: bash