on: [push, pull_request]
name: MonoRepo

env:
  PROJECT_ID: ${{ secrets.RUN_PROJECT }}
  SERVICE_NAME:  ${{ secrets.SERVICE_NAME }}

jobs:
  test:
    strategy:
      matrix:
        go-version: [1.16.x]
        # os: [ubuntu-latest, macos-latest, windows-latest]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
        os: ubuntu-latest
    
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Run test
      run: go run services/user/main.go
    
    # Setup gcloud CLI
    - uses: google-github-actions/setup-gcloud@master
      with:
        version: '286.0.0'
        service_account_email: ${{ secrets.RUN_SA_EMAIL }}
        service_account_key: ${{ secrets.RUN_SA_KEY }}
        project_id: ${{ secrets.RUN_PROJECT }}

    # Build and push image to Google Container Registry
    - name: Build
      run: |-
        gcloud builds submit \
          --quiet \
          --tag "gcr.io/$PROJECT_ID/$SERVICE_NAME:$GITHUB_SHA"

