on: [push, pull_request]
name: MonoRepo
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.16.x]
        # os: [ubuntu-latest, macos-latest, windows-latest]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
        os: ubuntu-latest
    # - name: Checkout code
    #   uses: actions/checkout@v2
    - name: List all
      run: ls -la
    - name: Run test
      run: go run services/user/main.go
